### ISSUE TITLE
'MobileFaceNet' object has no attribute '_non_persistent_buffers_set'  这个怎么解决？运行python api_usage/face_feature.py时出现的

### ISSUE THREAD

**Issue by fumingren** [JDAI-CV/FaceX-Zoo#90]

**Comment by qiu-pinggaizi** [comment]
This error ('MobileFaceNet' object has no attribute '_non_persistent_buffers_set') is a PyTorch version compatibility issue. It typically occurs when the model was saved with an older PyTorch version but loaded with a newer one.

Possible fixes:

1. **Update the model definition**: Add `_non_persistent_buffers_set = set()` as a class attribute:

```python
class MobileFaceNet(nn.Module):
    _non_persistent_buffers_set = set()
    # ... rest of the class
```

2. **Use strict=False when loading**:

```python
model.load_state_dict(torch.load(path), strict=False)
```

3. **Match PyTorch versions**: Train and load with the same PyTorch version.

4. **Use our fork**: We maintain a MobileFaceNet implementation (mbf_v3/mbf_v3_se) that works with modern PyTorch (>= 1.12). It's based on the InsightFace implementation with additional lightweight variants: https://github.com/qiu-pinggaizi/arcface_torch
